# Generated by Django 5.2.12 on 2026-03-17 15:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории товаров.', max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название торгового оборудования.', max_length=255, verbose_name='Название')),
                ('pos_x', models.FloatField(help_text='Координата X на плане магазина (единица измерения по договорённости).', verbose_name='Позиция X')),
                ('pos_y', models.FloatField(help_text='Координата Y на плане магазина (единица измерения по договорённости).', verbose_name='Позиция Y')),
                ('rotation', models.FloatField(default=0.0, help_text='Поворот оборудования на плане (в градусах).', verbose_name='Поворот')),
                ('width', models.FloatField(help_text='Ширина оборудования в миллиметрах.', verbose_name='Ширина (мм)')),
                ('height', models.FloatField(help_text='Высота оборудования в миллиметрах.', verbose_name='Высота (мм)')),
                ('depth', models.FloatField(help_text='Глубина оборудования в миллиметрах.', verbose_name='Глубина (мм)')),
                ('display_logic', models.CharField(choices=[('surface', 'Полка'), ('linear', 'Вешалка'), ('bulk', 'Емкость'), ('grid', 'Сетка/Крючки'), ('spot', 'Экспозиция')], default='surface', help_text='Логика расчёта размещения товаров на оборудовании.', max_length=20, verbose_name='Логика выкладки')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название магазина.', max_length=255, verbose_name='Название')),
                ('address', models.CharField(help_text='Фактический адрес магазина.', max_length=500, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи магазина.', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название товара.', max_length=255, verbose_name='Название')),
                ('sku', models.CharField(help_text='Артикул (SKU) товара.', max_length=64, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена товара (в валюте проекта).', max_digits=12, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, help_text='Изображение товара.', null=True, upload_to='products/', verbose_name='Изображение')),
                ('width', models.FloatField(help_text='Ширина товара в миллиметрах.', verbose_name='Ширина (мм)')),
                ('height', models.FloatField(help_text='Высота товара в миллиметрах.', verbose_name='Высота (мм)')),
                ('depth', models.FloatField(help_text='Глубина товара в миллиметрах.', verbose_name='Глубина (мм)')),
                ('weight', models.FloatField(help_text='Вес товара (единица измерения по договорённости, например граммы).', verbose_name='Вес')),
                ('category', models.ForeignKey(help_text='Категория, к которой относится товар.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ShelfLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(help_text='Порядковый номер уровня/полки.', verbose_name='Номер уровня')),
                ('width', models.FloatField(help_text='Ширина уровня в миллиметрах.', verbose_name='Ширина (мм)')),
                ('height', models.FloatField(help_text='Высота уровня в миллиметрах.', verbose_name='Высота (мм)')),
                ('depth', models.FloatField(help_text='Глубина уровня в миллиметрах.', verbose_name='Глубина (мм)')),
                ('hooks_count', models.IntegerField(default=0, help_text='Количество крючков для сетки/крючков (grid).', verbose_name='Количество крючков')),
                ('equipment', models.ForeignKey(help_text='Оборудование, к которому относится уровень/полка.', on_delete=django.db.models.deletion.CASCADE, related_name='shelf_levels', to='core.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Уровень/полка',
                'verbose_name_plural': 'Уровни/полки',
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(help_text='Товар, размещённый на уровне/полке.', on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='core.product', verbose_name='Товар')),
                ('shelf_level', models.ForeignKey(help_text='Уровень оборудования, на котором размещён товар.', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='core.shelflevel', verbose_name='Уровень/полка')),
            ],
            options={
                'verbose_name': 'Размещение (планограмма)',
                'verbose_name_plural': 'Размещения (планограмма)',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='store',
            field=models.ForeignKey(help_text='Магазин, в котором установлено оборудование.', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.store', verbose_name='Магазин'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Администратор сети'), ('manager', 'Менеджер магазина'), ('staff', 'Мерчандайзер')], default='staff', help_text='Роль пользователя в системе.', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, help_text='Контактный номер телефона пользователя.', max_length=30, null=True, verbose_name='Телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('store', models.ForeignKey(blank=True, help_text='Магазин, к которому привязан пользователь (если применимо).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Короткое название задачи.', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, help_text='Подробное описание задачи.', verbose_name='Описание')),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В работе'), ('done', 'Готово')], default='todo', help_text='Текущий статус задачи.', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания задачи.', verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Дата и время завершения задачи.', null=True, verbose_name='Дата завершения')),
                ('report_photo', models.ImageField(blank=True, help_text='Фотография отчёта о выполнении задачи.', null=True, upload_to='task_reports/', verbose_name='Фото отчёта')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Пользователь, которому назначена задача.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('placement', models.ForeignKey(blank=True, help_text='Размещение (планограмма), к которому относится задача.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.placement', verbose_name='Размещение')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.AddConstraint(
            model_name='shelflevel',
            constraint=models.UniqueConstraint(fields=('equipment', 'level_number'), name='uniq_shelflevel_equipment_level_number'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.UniqueConstraint(fields=('shelf_level', 'product'), name='uniq_placement_shelflevel_product'),
        ),
    ]
