# Generated by Django 5.2.12 on 2026-04-02 20:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_supplyorder_supplyorderitem_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Себестоимость единицы в рамках этой партии.', max_digits=12, verbose_name='Закупочная цена')),
                ('initial_quantity', models.PositiveIntegerField(help_text='Количество при первичной приёмке в партию.', verbose_name='Начальное количество')),
                ('current_quantity', models.PositiveIntegerField(help_text='Остаток по партии с учётом списаний и перемещений.', verbose_name='Текущее количество в партии')),
                ('manufacture_date', models.DateField(blank=True, help_text='Дата выпуска (если есть на маркировке).', null=True, verbose_name='Дата производства')),
                ('expiration_date', models.DateField(help_text='Крайняя дата годности; обязательна для контроля FEFO.', verbose_name='Срок годности')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные партии исключаются из подбора под новые операции.', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Запись партии в системе.', verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Партия товара',
                'verbose_name_plural': 'Партии товаров',
                'ordering': ('expiration_date', 'pk'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='uniq_inventory_store_product',
        ),
        migrations.RemoveField(
            model_name='supplyorderitem',
            name='actual_quantity',
        ),
        migrations.RemoveField(
            model_name='supplyorderitem',
            name='expected_quantity',
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Итоговая сумма заказа (валюта проекта; может совпадать с суммой позиций).', max_digits=12, verbose_name='Сумма закупки'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Договорная закупочная цена за единицу в этой строке.', max_digits=12, verbose_name='Цена за единицу'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Заказанное количество единиц по строке.', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи в системе.', verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Наименование организации (тенанта / юрлица).', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(help_text='Товарный SKU.', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Количество единиц товара по данной записи.', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('ordered', 'Заказано'), ('warehouse', 'На складе'), ('shelf', 'На витрине')], default='warehouse', help_text='Где физически учитывается товар: заказ, склад или витрина.', max_length=20, verbose_name='Статус нахождения'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(help_text='Торговая точка, где отражаются остатки.', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='core.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Время последнего изменения записи.', verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='company',
            field=models.ForeignKey(help_text='Организация-заказчик поставки.', on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to='core.company', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заказа.', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, оформивший заказ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supply_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='Время фактической приёмки по складу/магазину.', null=True, verbose_name='Принят'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ordered', 'В пути'), ('received', 'Принят'), ('cancelled', 'Отменен')], default='draft', help_text='Этап жизненного цикла заказа поставщику.', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='store',
            field=models.ForeignKey(help_text='Магазин назначения: куда везут товар.', on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to='core.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='supplyorderitem',
            name='order',
            field=models.ForeignKey(help_text='Заказ поставщику, к которому относится строка.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.supplyorder', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='supplyorderitem',
            name='product',
            field=models.ForeignKey(help_text='Товар в строке заказа.', on_delete=django.db.models.deletion.CASCADE, related_name='supply_order_items', to='core.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(help_text='Номенклатура в партии.', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='store',
            field=models.ForeignKey(help_text='Точка, где учитывается остаток партии.', on_delete=django.db.models.deletion.CASCADE, related_name='product_batches', to='core.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='supply_item',
            field=models.ForeignKey(blank=True, help_text='Строка заказа поставщику, по которой оприходована партия (если применимо).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.supplyorderitem', verbose_name='Позиция заказа поставки'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Партия, из которой образован этот остаток (FEFO/FIFO, полка/склад).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lines', to='core.productbatch', verbose_name='Партия'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True)), fields=('store', 'product'), name='uniq_inventory_store_product_no_batch'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False)), fields=('store', 'product', 'batch'), name='uniq_inventory_store_product_batch'),
        ),
    ]
