# Generated by Django 5.2.12 on 2026-04-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_batch_tracking_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyorderitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Договорная закупочная цена за единицу в этой строке.', max_digits=12, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='supplyorderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Заказанное количество единиц по строке.', verbose_name='Количество'),
        ),
    ]
