# Generated by Django 5.2.12 on 2026-04-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supplyorderitem_no_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_marked',
            field=models.BooleanField(default=False, help_text='Товар с обязательной маркировкой (например, «Честный ЗНАК»).', verbose_name='Маркированный товар'),
        ),
    ]
