# Generated by Django 5.2.12 on 2026-05-02 00:35

import django.db.models.deletion
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def copy_price_per_unit_to_purchase_price(apps, schema_editor):
    SupplyOrderItem = apps.get_model("core", "SupplyOrderItem")
    for row in SupplyOrderItem.objects.all():
        old = getattr(row, "price_per_unit", None)
        if old is not None:
            row.purchase_price = old
            row.save(update_fields=["purchase_price"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_product_is_marked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Наименование поставщика.",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True,
                        help_text="Телефон, e-mail, адрес и другие контакты.",
                        verbose_name="Контактные данные",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        help_text="Идентификационный номер налогоплательщика (ИНН).",
                        max_length=12,
                        verbose_name="ИНН",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
        migrations.AddField(
            model_name="supplyorder",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, зафиксировавший приёмку на складе/в магазине.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_supply_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем принят",
            ),
        ),
        migrations.AddField(
            model_name="supplyorder",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Фактическая сумма при приёмке: Σ (факт × закупочная цена по строке).",
                max_digits=10,
                verbose_name="Общая стоимость закупки",
            ),
        ),
        migrations.AddField(
            model_name="supplyorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Поставщик по договору (если указан).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supply_orders",
                to="core.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="supplyorderitem",
            name="actual_quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Фактически принятое количество (заполняется при приёмке).",
                verbose_name="Фактическое количество",
            ),
        ),
        migrations.AddField(
            model_name="supplyorderitem",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Закупочная цена за единицу товара в этой строке.",
                max_digits=10,
                verbose_name="Цена закупки за единицу",
            ),
        ),
        migrations.RunPython(copy_price_per_unit_to_purchase_price, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="supplyorderitem",
            name="price_per_unit",
        ),
        migrations.AlterField(
            model_name="productbatch",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Себестоимость единицы в рамках этой партии.",
                max_digits=10,
                verbose_name="Закупочная цена",
            ),
        ),
        migrations.AlterField(
            model_name="supplyorderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                help_text="Заказанное количество единиц по строке.",
                verbose_name="Ожидаемое количество",
            ),
        ),
    ]
