# Generated by Django 5.2.12 on 2026-05-04 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_digital_twin_zone_equipment_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, help_text='Глобальный номер товарной единицы (14 цифр), маркировка Честный ЗНАК / GS1.', max_length=14, null=True, unique=True, verbose_name='GTIN'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Идентификатор единицы маркированного товара (AI 21 в Data Matrix).', max_length=50, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('ordered', 'Заказано'), ('warehouse', 'На складе'), ('shelf', 'На витрине')], default='warehouse', help_text='Где физически учитывается товар; при заполненной полке «shelf» местоположение в первую очередь определяется по цифровому плану зала.', max_length=20, verbose_name='Статус нахождения'),
        ),
        migrations.AlterField(
            model_name='planogramequipment',
            name='store',
            field=models.ForeignKey(help_text='Магазин, в котором установлено оборудование.', on_delete=django.db.models.deletion.CASCADE, related_name='planogram_equipment', to='core.store', verbose_name='Магазин'),
        ),
    ]
