# Generated by Django 5.2.12 on 2026-05-11 02:55

from django.db import migrations, models


def forwards_role_migration(apps, schema_editor):
    User = apps.get_model("core", "User")
    # Prefer preserving admin access for superusers
    User.objects.filter(is_superuser=True).update(role="admin")
    # legacy: staff/manager -> employee (avoid overwriting superusers)
    User.objects.filter(role__in=["staff", "manager"]).exclude(is_superuser=True).update(role="employee")


def backwards_role_migration(apps, schema_editor):
    User = apps.get_model("core", "User")
    # best-effort: employee -> staff
    User.objects.filter(role="employee").update(role="staff")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_equipment_floor_plan_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('employee', 'Работник торгового зала')], default='employee', help_text='Роль пользователя в системе.', max_length=20, verbose_name='Роль'),
        ),
        migrations.RunPython(forwards_role_migration, backwards_role_migration),
    ]
