# Generated by Django 5.2.12 on 2026-05-11 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Сколько единиц товара выложить.', verbose_name='Количество')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('COMPLETED', 'Выполнена')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('equipment', models.ForeignKey(help_text='Стеллаж, холодильник и т.п., куда нужно отнести товар.', on_delete=django.db.models.deletion.CASCADE, related_name='placement_tasks', to='core.equipment', verbose_name='Оборудование')),
                ('product', models.ForeignKey(help_text='Товар, который нужно выложить.', on_delete=django.db.models.deletion.CASCADE, related_name='placement_tasks', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Задача на выкладку',
                'verbose_name_plural': 'Задачи на выкладку',
                'ordering': ('-created_at',),
            },
        ),
    ]
