# Generated by Django 5.2.12 on 2026-05-11 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_placement_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Сколько единиц доступно для выкладки со склада.', verbose_name='Количество на складе')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складе',
            },
        ),
        migrations.CreateModel(
            name='Planogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity', models.PositiveIntegerField(help_text='Сколько единиц товара должно находиться на полке в идеале.', verbose_name='Целевое количество')),
                ('equipment', models.ForeignKey(help_text='Объект плана зала (стеллаж, холодильник и т.п.).', on_delete=django.db.models.deletion.CASCADE, related_name='planograms', to='core.equipment', verbose_name='Оборудование')),
                ('product', models.ForeignKey(help_text='Товар, который должен быть представлен на этом оборудовании.', on_delete=django.db.models.deletion.CASCADE, related_name='floor_planograms', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Планограмма (зал)',
                'verbose_name_plural': 'Планограммы (зал)',
            },
        ),
        migrations.AddField(
            model_name='placementtask',
            name='planogram',
            field=models.ForeignKey(blank=True, help_text='Источник задачи; пусто для устаревших записей до введения планограмм.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_tasks', to='core.planogram', verbose_name='Планограмма'),
        ),
        migrations.AddConstraint(
            model_name='placementtask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('planogram',), name='uniq_placementtask_pending_planogram'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='core.product', verbose_name='Товар'),
        ),
        migrations.AddConstraint(
            model_name='planogram',
            constraint=models.UniqueConstraint(fields=('equipment', 'product'), name='uniq_planogram_equipment_product'),
        ),
    ]
