# Generated by Django 5.2.12 on 2026-05-11 06:45

import django.db.models.deletion
from django.db import migrations, models


def _forwards(apps, schema_editor):
    Equipment = apps.get_model('core', 'Equipment')
    EquipmentSlot = apps.get_model('core', 'EquipmentSlot')
    Planogram = apps.get_model('core', 'Planogram')

    def ensure_slots(equipment):
        if EquipmentSlot.objects.filter(equipment_id=equipment.id).exists():
            return
        eq_type = str(getattr(equipment, 'type', 'shelving'))
        rows = int(getattr(equipment, 'rows_count', 0) or 0)

        if eq_type in ('shelving', 'fridge', 'shelf'):
            rows = rows if rows > 0 else 4
            for r in range(rows):
                for c in range(4):
                    EquipmentSlot.objects.create(
                        equipment_id=equipment.id,
                        row_index=r,
                        col_index=c,
                        width_percent=25.0,
                    )
            return

        if eq_type == 'pallet':
            EquipmentSlot.objects.create(
                equipment_id=equipment.id,
                row_index=0,
                col_index=0,
                width_percent=100.0,
            )
            return

        if eq_type == 'pegboard':
            rows = rows if rows > 0 else 3
            for r in range(rows):
                for c in range(5):
                    EquipmentSlot.objects.create(
                        equipment_id=equipment.id,
                        row_index=r,
                        col_index=c,
                        width_percent=20.0,
                    )
            return

        # display/прочее: 1x4
        for c in range(4):
            EquipmentSlot.objects.create(
                equipment_id=equipment.id,
                row_index=0,
                col_index=c,
                width_percent=25.0,
            )

    for eq in Equipment.objects.all():
        ensure_slots(eq)

    # Перенос старых планограмм: привяжем к первому слоту оборудования.
    for pg in Planogram.objects.filter(slot__isnull=True).exclude(equipment__isnull=True):
        first_slot = (
            EquipmentSlot.objects.filter(equipment_id=pg.equipment_id)
            .order_by('row_index', 'col_index', 'id')
            .first()
        )
        if first_slot:
            pg.slot_id = first_slot.id
            pg.save(update_fields=['slot'])
        else:
            # Если вдруг слоты не создались, удаляем планограмму (тестовая БД/переходный этап).
            pg.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_planogram_stock_and_task_planogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(help_text='Номер полки/ряда, начиная с 0.', verbose_name='Индекс ряда')),
                ('col_index', models.PositiveIntegerField(help_text='Порядковый номер ячейки в ряду, начиная с 0.', verbose_name='Индекс ячейки')),
                ('width_percent', models.FloatField(default=25.0, help_text='Ширина ячейки в процентах от ширины ряда/полки.', verbose_name='Ширина (%)')),
            ],
            options={
                'verbose_name': 'Слот оборудования',
                'verbose_name_plural': 'Слоты оборудования',
                'ordering': ('equipment_id', 'row_index', 'col_index'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='planogram',
            name='uniq_planogram_equipment_product',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='shelf_count',
            new_name='rows_count',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rows_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество уровней для визуализации и слотов: для стеллажа — полки, для перфопанели — ряды крючков, для паллеты обычно 1.', verbose_name='Число рядов/уровней'),
        ),
        migrations.AddField(
            model_name='equipmentslot',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='planogram',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='Слот на оборудовании, куда должен выкладываться товар.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planograms', to='core.equipmentslot', verbose_name='Слот'),
        ),
        migrations.RunPython(
            code=_forwards,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='planogram',
            name='equipment',
        ),
        migrations.AddConstraint(
            model_name='planogram',
            constraint=models.UniqueConstraint(fields=('slot', 'product'), name='uniq_planogram_slot_product'),
        ),
        migrations.AddConstraint(
            model_name='equipmentslot',
            constraint=models.UniqueConstraint(fields=('equipment', 'row_index', 'col_index'), name='uniq_equipment_slot_row_col'),
        ),
    ]
