# Generated by Django 5.2.12 on 2026-05-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_planogram_slot_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('IN_PROGRESS', 'Выполняется'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменена')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
    ]
