# Generated by Django 5.2.12 on 2026-05-30 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _backfill_qr_tokens(apps):
    EquipmentSlot = apps.get_model("core", "EquipmentSlot")
    for slot in EquipmentSlot.objects.all():
        slot.qr_token = uuid.uuid4()
        slot.save(update_fields=["qr_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_placementtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentslot',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID для QR-кода полки; сканируется при верификации выкладки.', null=True, verbose_name='QR-токен'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _backfill_qr_tokens(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID для QR-кода полки; сканируется при верификации выкладки.', unique=True, verbose_name='QR-токен'),
        ),
        migrations.AddField(
            model_name='placementtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='placementtask',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Партия, зарезервированная при создании задачи.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_tasks', to='core.productbatch', verbose_name='Партия (FEFO)'),
        ),
        migrations.AddField(
            model_name='placementtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершена'),
        ),
        migrations.AddField(
            model_name='placementtask',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Фото отчёта (URL)'),
        ),
        migrations.AddField(
            model_name='placementtask',
            name='slot_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QR слота подтверждён'),
        ),
        migrations.CreateModel(
            name='LegacyPlanogramTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Короткое название задачи.', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, help_text='Подробное описание задачи.', verbose_name='Описание')),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В работе'), ('done', 'Готово')], default='todo', help_text='Текущий статус задачи.', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания задачи.', verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Дата и время завершения задачи.', null=True, verbose_name='Дата завершения')),
                ('report_photo', models.ImageField(blank=True, help_text='Фотография отчёта о выполнении задачи.', null=True, upload_to='task_reports/', verbose_name='Фото отчёта')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Пользователь, которому назначена задача.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_planogram_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('placement', models.ForeignKey(blank=True, help_text='Размещение (планограмма), к которому относится задача.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_tasks', to='core.placement', verbose_name='Размещение')),
            ],
            options={
                'verbose_name': 'Задача (legacy планограмма)',
                'verbose_name_plural': 'Задачи (legacy планограмма)',
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('IN_PROGRESS', 'Выполняется'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='CREATED', max_length=20, verbose_name='Статус')),
                ('requires_photo', models.BooleanField(default=False, verbose_name='Требуется фотоотчёт')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Фото отчёта (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_staff_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='core.equipment', verbose_name='Оборудование')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='core.equipmentslot', verbose_name='Слот')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='core.zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Поручение сотруднику',
                'verbose_name_plural': 'Поручения сотрудникам',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('staff_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.stafftask', verbose_name='Поручение')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ('created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
