# Generated by Django 5.2.12 on 2026-05-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contour_c_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Изображение (URL)'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
