# Generated by Django 5.2.12 on 2026-06-02 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_shelf_write_off'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placement',
            options={'verbose_name': 'Legacy: размещение', 'verbose_name_plural': 'Legacy: размещения (не использовать)'},
        ),
        migrations.AlterModelOptions(
            name='planogramequipment',
            options={'verbose_name': 'Legacy: оборудование планограммы', 'verbose_name_plural': 'Legacy: оборудование планограммы (не использовать)'},
        ),
        migrations.AlterModelOptions(
            name='shelflevel',
            options={'verbose_name': 'Legacy: уровень планограммы', 'verbose_name_plural': 'Legacy: уровни планограммы (не использовать)'},
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='has_discrepancies',
            field=models.BooleanField(default=False, help_text='Фактическое количество хотя бы по одной строке отличается от заказанного.', verbose_name='Есть расхождения'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='discrepancy_note',
            field=models.TextField(blank=True, help_text='Комментарий сотрудника, если факт ≠ заказ.', verbose_name='Примечание по расхождению'),
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='current_qty',
            field=models.PositiveIntegerField(default=0, help_text='Сколько единиц товара сейчас на слоте (витрина).', verbose_name='Текущий остаток на полке'),
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Рассчитанная вместимость слота для SKU планограммы.', verbose_name='Макс. вместимость'),
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='shelf',
            field=models.ForeignKey(blank=True, help_text='Полка с габаритами для расчёта вместимости; если пусто — по row_index.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_slots', to='core.shelf', verbose_name='Физическая полка'),
        ),
        migrations.CreateModel(
            name='SupplyReceivingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('IN_PROGRESS', 'Выполняется'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='CREATED', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_receiving_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supply_receiving_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
                ('supply_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_task', to='core.supplyorder', verbose_name='Заказ поставщику')),
            ],
            options={
                'verbose_name': 'Задача приёмки заказа',
                'verbose_name_plural': 'Задачи приёмки заказов',
                'ordering': ('-created_at',),
            },
        ),
    ]
