# Generated by Django 5.2.12 on 2026-06-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_supply_receiving_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyorder',
            name='planned_receiving_date',
            field=models.DateField(blank=True, help_text='Ожидаемая дата поступления товара на склад (план менеджера).', null=True, verbose_name='Плановая дата приёмки'),
        ),
    ]
