# Generated by Django 5.2.12 on 2026-06-14 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_product_shelf_life_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfClearingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Сколько единиц убрать с полки на склад.', verbose_name='Количество')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('PENDING', 'Ожидает'), ('IN_PROGRESS', 'Выполняется'), ('COMPLETED', 'Завершено'), ('FAILED', 'Проблема'), ('CANCELLED', 'Отменена')], default='CREATED', max_length=20, verbose_name='Статус')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Фото отчёта (URL)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearing_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearing_tasks', to='core.productbatch', verbose_name='Партия для возврата')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearing_tasks', to='core.equipment', verbose_name='Оборудование')),
                ('planogram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearing_tasks', to='core.planogram', verbose_name='Планограмма')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearing_tasks', to='core.product', verbose_name='Товар')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearing_tasks', to='core.equipmentslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Задача уборки на склад',
                'verbose_name_plural': 'Задачи уборки на склад',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'CREATED')), fields=('planogram',), name='uniq_clearingtask_created_planogram')],
            },
        ),
    ]
