# Generated by Django 5.2.12 on 2026-06-14 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_shelf_clearing_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfwriteoff',
            name='reason',
            field=models.CharField(choices=[('EXPIRED_PLACEMENT_BATCH', 'Просрочена партия последней выкладки'), ('EXPIRED_BATCH', 'Просроченная партия'), ('MANUAL', 'Ручное списание')], default='EXPIRED_PLACEMENT_BATCH', max_length=40, verbose_name='Причина'),
        ),
        migrations.CreateModel(
            name='WriteOffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('PENDING', 'Ожидает'), ('IN_PROGRESS', 'Выполняется'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменена')], default='CREATED', max_length=20, verbose_name='Статус')),
                ('location', models.CharField(choices=[('WAREHOUSE', 'Склад'), ('SHELF', 'Полка')], max_length=20, verbose_name='Место списания')),
                ('trigger', models.CharField(choices=[('EXPIRED_AUTO', 'Просрочка (авто)'), ('MANUAL', 'Ручное списание')], default='EXPIRED_AUTO', max_length=20, verbose_name='Источник')),
                ('reason', models.TextField(blank=True, verbose_name='Причина / комментарий')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Фото отчёта (URL)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_off_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_off_tasks', to='core.productbatch', verbose_name='Партия')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_write_off_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_off_tasks', to='core.equipment', verbose_name='Оборудование')),
                ('placement_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_off_tasks', to='core.placementtask', verbose_name='Задача выкладки')),
                ('planogram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_off_tasks', to='core.planogram', verbose_name='Планограмма')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_off_tasks', to='core.product', verbose_name='Товар')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_off_tasks', to='core.equipmentslot', verbose_name='Слот')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_off_tasks', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Задача на списание',
                'verbose_name_plural': 'Задачи на списание',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WarehouseWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Списано, шт.')),
                ('reason', models.CharField(choices=[('EXPIRED_BATCH', 'Просроченная партия'), ('MANUAL', 'Ручное списание')], default='EXPIRED_BATCH', max_length=40, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_write_offs', to='core.productbatch', verbose_name='Партия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_write_offs', to='core.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_write_offs', to='core.store', verbose_name='Магазин')),
                ('write_off_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_write_offs', to='core.writeofftask', verbose_name='Задача списания')),
            ],
            options={
                'verbose_name': 'Списание со склада',
                'verbose_name_plural': 'Списания со склада',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='shelfwriteoff',
            name='write_off_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_write_offs', to='core.writeofftask', verbose_name='Задача списания'),
        ),
        migrations.AddConstraint(
            model_name='writeofftask',
            constraint=models.UniqueConstraint(condition=models.Q(('location', 'WAREHOUSE'), ('status', 'CREATED')), fields=('batch',), name='uniq_writeofftask_created_warehouse_batch'),
        ),
        migrations.AddConstraint(
            model_name='writeofftask',
            constraint=models.UniqueConstraint(condition=models.Q(('location', 'SHELF'), ('status', 'CREATED')), fields=('batch', 'slot'), name='uniq_writeofftask_created_shelf_batch_slot'),
        ),
    ]
