# Generated by Django 5.2.12 on 2026-06-14 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_write_off_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTaskScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='Время скана')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_scans', to='core.productbatch', verbose_name='Партия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_scans', to='core.product', verbose_name='Товар')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_scans', to=settings.AUTH_USER_MODEL, verbose_name='Сканировал')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.placementtask', verbose_name='Задача выкладки')),
            ],
            options={
                'verbose_name': 'Скан выкладки',
                'verbose_name_plural': 'Сканы выкладки',
                'ordering': ('scanned_at', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('serial_number__isnull', False)), fields=('task', 'serial_number'), name='uniq_placement_scan_task_serial')],
            },
        ),
    ]
