# Generated by Django 5.2.12 on 2026-06-14 22:49

import django.core.validators
from django.db import migrations, models


def set_default_bulk_density(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    Product.objects.filter(sale_unit="weight", bulk_density__isnull=True).update(
        bulk_density=550.0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_supply_order_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_density',
            field=models.FloatField(blank=True, help_text='Для товаров на развес в корзине (BOX).', null=True, verbose_name='Насыпная плотность (кг/м³)'),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_coefficient',
            field=models.FloatField(default=0.6, help_text='Доля объёма слота, занимаемая товаром при навале (BOX, штучный).', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='Коэффициент укладки'),
        ),
        migrations.RunPython(set_default_bulk_density, migrations.RunPython.noop),
    ]
